# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Zweden - Lonen en Inflatie
author: Amora van Deursen, Emilie Rosier, May Bardet, Sabih Syed

execute:
  execute_notebooks: "off"  # Geen notebooks uitvoeren bij build

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/prox05/IV-KI-2025/
  path_to_book: docs
  branch: main

html:
  show_input: false         # ⛔️ Verberg de code-input op pagina's
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
